language: node_js
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH=$HOME/.yarn/bin:$PATH
script: yarn coveralls
node_js:
  - 8.11.0
  - 12.1.0
  - node
